### ISSUE TITLE
Adding ZNC to elfhosted?

### ISSUE THREAD

**Issue by 123140129518158215121528157185189561** [elfhosted/enhancements#5]
I would love for ZNC to be added to Elfhosted one day! It has a docker container. Only issue with adding it, I could see is the Signed SSL certificate. Cant seem to find a seedbox provider or app provider or anyone that will let me use custom domain and add Signed SSL certificate to irc access url. Wiki links etc below:
https://wiki.znc.in/ZNC
https://wiki.znc.in/Signed_SSL_certificate
https://docs.linuxserver.io/images/docker-znc/

**Comment by funkypenguin** [comment]
I've had a quick look, it seems as if ZNC is intended to be connected to directly via TCP, rather than as an HTTP/S frontend. I'm afraid ElfHosted's design only supports HTTP proxy-able interfaces - we can't expose TCP ports directly to your apps. 

Unless I'm wrong about how ZNC works, I'm afraid this'll be a non-starter.

We do have TheLounge though, which some users use for "disconnectable" IRC sessions : https://elfhosted.com/app/thelounge/

D
